// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.ApplicationLogController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.ApplicationConfigController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Program.Main(System.String[])")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.NewScheduler(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.AddNewScheduledTrigger(ManagedApplicationScheduler.Services.Models.SchedulerUsageViewModel)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.DeleteSchedulerItem(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.SchedulerLogDetail(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.SchedulerController.SubscriptionMeteredDetail(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.Subscriptions~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Usage", "CA2253:Named placeholders should not be numeric values", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.Subscriptions~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.SubscriptionDetails(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.NewSubscription~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.NewSubscriptionAction(ManagedApplicationScheduler.Services.Models.SubscriptionModel)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.Subscribe(System.String)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.Unsubscribe(System.String)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.EditSubscription(System.String)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.EditSubscriptionAction(ManagedApplicationScheduler.Services.Models.SubscriptionModel)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "<Pending>", Scope = "member", Target = "~M:ManagedApplicationScheduler.AdminSite.Controllers.HomeController.DeleteSubscription(System.String)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:ManagedApplicationScheduler.AdminSite.Program")]
